---
env:
  es6: true
  node: true
  browser: true
extends:
  - airbnb-base
  - plugin:prettier/recommended
parser: '@babel/eslint-parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: 'module'
rules:
  max-len: 0
  import/no-extraneous-dependencies: 0
  no-restricted-syntax: 0
  no-await-in-loop: 0
