---
env:
  es6: true
  node: true
  browser: true
extends:
  - airbnb-base
  - plugin:prettier/recommended
globals:
  lozad: true
rules:
  max-len: 0
  import/no-extraneous-dependencies: 0
  no-restricted-syntax: 0
  no-await-in-loop: 0
