module.exports = [
  // {
  //   family: 'Plex Mono',
  //   file: 'plex-mono-thin',
  //   weight: '100',
  //   style: 'normal',
  // },
  // {
  //   family: 'Plex Mono',
  //   file: 'plex-mono-thin-italic',
  //   weight: '100',
  //   style: 'italic',
  // },
  // {
  //   family: 'Plex Mono',
  //   file: 'plex-mono-extralight',
  //   weight: '200',
  //   style: 'normal',
  // },
  // {
  //   family: 'Plex Mono',
  //   file: 'plex-mono-extralight-italic',
  //   weight: '200',
  //   style: 'italic',
  // },
  // {
  //   family: 'Plex Mono',
  //   file: 'plex-mono-light',
  //   weight: '300',
  //   style: 'italic',
  // },
  // {
  //   family: 'Plex Mono',
  //   file: 'plex-mono-light-italic',
  //   weight: '300',
  //   style: 'italic',
  // },
  {
    family: 'Plex Mono',
    file: 'plex-mono-regular',
    weight: '400',
    style: 'normal',
  },
  {
    family: 'Plex Mono',
    file: 'plex-mono-italic',
    weight: '400',
    style: 'italic',
  },
  // {
  //   family: 'Plex Mono',
  //   file: 'plex-mono-text',
  //   weight: '400',
  //   style: 'normal',
  // },
  // {
  //   family: 'Plex Mono',
  //   file: 'plex-mono-text-italic',
  //   weight: '400',
  //   style: 'italic',
  // },
  // {
  //   family: 'Plex Mono',
  //   file: 'plex-mono-medium',
  //   weight: '500',
  //   style: 'normal',
  // },
  // {
  //   family: 'Plex Mono',
  //   file: 'plex-mono-medium-italic',
  //   weight: '500',
  //   style: 'italic',
  // },
  // {
  //   family: 'Plex Mono',
  //   file: 'plex-mono-semibold',
  //   weight: '600',
  //   style: 'normal',
  // },
  // {
  //   family: 'Plex Mono',
  //   file: 'plex-mono-semibold-italic',
  //   weight: '600',
  //   style: 'italic',
  // },
  {
    family: 'Plex Mono',
    file: 'plex-mono-bold',
    weight: '700',
    style: 'normal',
  },
  {
    family: 'Plex Mono',
    file: 'plex-mono-bold-italic',
    weight: '700',
    style: 'italic',
  },
  // {
  //   family: 'Plex Sans',
  //   file: 'plex-sans-thin',
  //   weight: '100',
  //   style: 'normal',
  // },
  // {
  //   family: 'Plex Sans',
  //   file: 'plex-sans-thin-italic',
  //   weight: '100',
  //   style: 'italic',
  // },
  // {
  //   family: 'Plex Sans',
  //   file: 'plex-sans-extralight',
  //   weight: '200',
  //   style: 'normal',
  // },
  // {
  //   family: 'Plex Sans',
  //   file: 'plex-sans-extralight-italic',
  //   weight: '200',
  //   style: 'italic',
  // },
  // {
  //   family: 'Plex Sans',
  //   file: 'plex-sans-light',
  //   weight: '300',
  //   style: 'normal',
  // },
  // {
  //   family: 'Plex Sans',
  //   file: 'plex-sans-light-italic',
  //   weight: '300',
  //   style: 'italic',
  // },
  {
    family: 'Plex Sans',
    file: 'plex-sans-regular',
    weight: '400',
    style: 'normal',
  },
  {
    family: 'Plex Sans',
    file: 'plex-sans-italic',
    weight: '400',
    style: 'italic',
  },
  // {
  //   family: 'Plex Sans',
  //   file: 'plex-sans-text',
  //   weight: '400',
  //   style: 'normal',
  // },
  // {
  //   family: 'Plex Sans',
  //   file: 'plex-sans-text-italic',
  //   weight: '400',
  //   style: 'italic',
  // },
  // {
  //   family: 'Plex Sans',
  //   file: 'plex-sans-medium',
  //   weight: '500',
  //   style: 'normal',
  // },
  // {
  //   family: 'Plex Sans',
  //   file: 'plex-sans-medium-italic',
  //   weight: '500',
  //   style: 'italic',
  // },
  // {
  //   family: 'Plex Sans',
  //   file: 'plex-sans-semibold',
  //   weight: '600',
  //   style: 'normal',
  // },
  // {
  //   family: 'Plex Sans',
  //   file: 'plex-sans-semibold-italic',
  //   weight: '600',
  //   style: 'italic',
  // },
  {
    family: 'Plex Sans',
    file: 'plex-sans-bold',
    weight: '700',
    style: 'normal',
  },
  // {
  //   family: 'Plex Sans',
  //   file: 'plex-sans-bold-italic',
  //   weight: '700',
  //   style: 'italic',
  // },
  // {
  //   family: 'Plex Serif',
  //   file: 'plex-serif-thin',
  //   weight: '100',
  //   style: 'normal',
  // },
  // {
  //   family: 'Plex Serif',
  //   file: 'plex-serif-thin-italic',
  //   weight: '100',
  //   style: 'italic',
  // },
  // {
  //   family: 'Plex Serif',
  //   file: 'plex-serif-extralight',
  //   weight: '200',
  //   style: 'normal',
  // },
  // {
  //   family: 'Plex Serif',
  //   file: 'plex-serif-extralight-italic',
  //   weight: '200',
  //   style: 'italic',
  // },
  // {
  //   family: 'Plex Serif',
  //   file: 'plex-serif-light',
  //   weight: '300',
  //   style: 'normal',
  // },
  // {
  //   family: 'Plex Serif',
  //   file: 'plex-serif-light-italic',
  //   weight: '300',
  //   style: 'italic',
  // },
  // {
  //   family: 'Plex Serif',
  //   file: 'plex-serif-regular',
  //   weight: '400',
  //   style: 'normal',
  // },
  {
    family: 'Plex Serif',
    file: 'plex-serif-italic',
    weight: '400',
    style: 'italic',
  },
  // {
  //   family: 'Plex Serif',
  //   file: 'plex-serif-text',
  //   weight: '400',
  //   style: 'normal',
  // },
  // {
  //   family: 'Plex Serif',
  //   file: 'plex-serif-text-italic',
  //   weight: '400',
  //   style: 'italic',
  // },
  // {
  //   family: 'Plex Serif',
  //   file: 'plex-serif-medium',
  //   weight: '500',
  //   style: 'normal',
  // },
  // {
  //   family: 'Plex Serif',
  //   file: 'plex-serif-medium-italic',
  //   weight: '500',
  //   style: 'italic',
  // },
  // {
  //   family: 'Plex Serif',
  //   file: 'plex-serif-semibold',
  //   weight: '600',
  //   style: 'normal',
  // },
  // {
  //   family: 'Plex Serif',
  //   file: 'plex-serif-semibold-italic',
  //   weight: '600',
  //   style: 'italic',
  // },
  // {
  //   family: 'Plex Serif',
  //   file: 'plex-serif-bold',
  //   weight: '700',
  //   style: 'normal',
  // },
  // {
  //   family: 'Plex Serif',
  //   file: 'plex-serif-bold-italic',
  //   weight: '700',
  //   style: 'italic',
  // },
  // { family: 'Poppins', file: 'poppins-thin', weight: '100', style: 'normal' },
  // {
  //   family: 'Poppins',
  //   file: 'poppins-thin-italic',
  //   weight: '100',
  //   style: 'italic',
  // },
  // {
  //   family: 'Poppins',
  //   file: 'poppins-extralight',
  //   weight: '200',
  //   style: 'normal',
  // },
  // {
  //   family: 'Poppins',
  //   file: 'poppins-extralight-italic',
  //   weight: '200',
  //   style: 'italic',
  // },
  // { family: 'Poppins', file: 'poppins-light', weight: '300', style: 'normal' },
  // {
  //   family: 'Poppins',
  //   file: 'poppins-light-italic',
  //   weight: '300',
  //   style: 'italic',
  // },
  // {
  //   family: 'Poppins',
  //   file: 'poppins-regular',
  //   weight: '400',
  //   style: 'normal',
  // },
  // { family: 'Poppins', file: 'poppins-italic', weight: '400', style: 'italic' },
  // { family: 'Poppins', file: 'poppins-medium', weight: '500', style: 'normal' },
  // {
  //   family: 'Poppins',
  //   file: 'poppins-medium-italic',
  //   weight: '500',
  //   style: 'italic',
  // },
  // {
  //   family: 'Poppins',
  //   file: 'poppins-semibold',
  //   weight: '600',
  //   style: 'normal',
  // },
  // {
  //   family: 'Poppins',
  //   file: 'poppins-semibold-italic',
  //   weight: '600',
  //   style: 'italic',
  // },
  // { family: 'Poppins', file: 'poppins-bold', weight: '700', style: 'normal' },
  // {
  //   family: 'Poppins',
  //   file: 'poppins-bold-italic',
  //   weight: '700',
  //   style: 'italic',
  // },
  // {
  //   family: 'Poppins',
  //   file: 'poppins-extrabold',
  //   weight: '800',
  //   style: 'normal',
  // },
  {
    family: 'Poppins',
    file: 'poppins-extrabold-italic',
    weight: '800',
    style: 'italic',
  },
  // { family: 'Poppins', file: 'poppins-black', weight: '900', style: 'normal' },
  // {
  //   family: 'Poppins',
  //   file: 'poppins-black-italic',
  //   weight: '900',
  //   style: 'italic',
  // },
];
